# Generated by Django 4.0.5 on 2022-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_turno', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cerrado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
